name: Kaggle Badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: "11 11 1 * *"  # 매월 1일 11:11 AM에 실행
  workflow_dispatch:

jobs:
  create-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: .github/actions/kaggle-badges
        run: npm install

      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome@131.0.6778.85

      - name: Generate Kaggle Badges
        uses: ./.github/actions/kaggle-badges
        with:
          username: hominlee

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./kaggle-badges/* ./kaggle-plates/* || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Kaggle badges"
          git push